title: "Top Down Modeling and HMI"
remote_theme: pmarsceill/just-the-docs
color_scheme: worldmodelers
search_enabled: true

aux_links:
  "MaaS on GitHub":
    - "//github.com/WorldModelers/ModelService"